// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crud_accounts.Models;

namespace crudAccounts.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20210224200323_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("crud_accounts.Models.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("uf")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Enderecos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7447105-ea62-4771-a355-7ac1ed141381"),
                            Bairro = "Centro",
                            Cep = "20260525",
                            Complemento = "casa 23",
                            Logradouro = "Rua Sete de Setembro",
                            Municipio = "Rio de Janeiro",
                            Numero = "15",
                            uf = "RJ"
                        },
                        new
                        {
                            Id = new Guid("448ae198-f4d7-4a97-8c30-bfba535b002d"),
                            Bairro = "Centro",
                            Cep = "11260525",
                            Complemento = "bloco 6 ap 306",
                            Logradouro = "Avenida Paulista",
                            Municipio = "São Paulo",
                            Numero = "1205",
                            uf = "SP"
                        },
                        new
                        {
                            Id = new Guid("4fc66958-bbd6-45d7-b102-80f149077eea"),
                            Bairro = "Bangu",
                            Cep = "21280525",
                            Complemento = "casa 5",
                            Logradouro = "Avenida Ministro Ary Franco",
                            Municipio = "Rio de Janeiro",
                            Numero = "2255",
                            uf = "RJ"
                        });
                });

            modelBuilder.Entity("crud_accounts.Models.EnderecoPessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cep")
                        .HasColumnType("int");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<Guid>("PessoaForeignKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("uf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PessoaForeignKey")
                        .IsUnique();

                    b.ToTable("EnderecoPessoa");
                });

            modelBuilder.Entity("crud_accounts.Models.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("634cefd1-c455-40c2-a0fd-6e6339a1f268"),
                            Cpf = "111548",
                            Nome = "Herb Hancock",
                            Rg = "21514151"
                        },
                        new
                        {
                            Id = new Guid("3fde07f1-fae8-4178-b456-2b91dd7bf42d"),
                            Cpf = "1252632545",
                            Nome = "Chick Corea",
                            Rg = "207255136"
                        },
                        new
                        {
                            Id = new Guid("2882353d-b88e-47a8-8122-41f4899854ab"),
                            Cpf = "111548",
                            Nome = "Charlie Parker",
                            Rg = "153526548"
                        });
                });

            modelBuilder.Entity("crud_accounts.Models.Telefone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Telefones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4657da0-4993-48b8-a2a8-6ec6322ddd6b"),
                            Numero = "985635241",
                            Tipo = "Celular"
                        },
                        new
                        {
                            Id = new Guid("ca8334ce-b16f-4542-8af3-c36ef0058b82"),
                            Numero = "975859654",
                            Tipo = "Celular"
                        },
                        new
                        {
                            Id = new Guid("1919ad87-d319-4ca3-8232-5cfe3abe4651"),
                            Numero = "312524684",
                            Tipo = "Fixo"
                        });
                });

            modelBuilder.Entity("crud_accounts.Models.TelefonePessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<Guid>("PessoaForeignKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PessoaForeignKey")
                        .IsUnique();

                    b.ToTable("TelefonePessoa");
                });

            modelBuilder.Entity("crud_accounts.Models.EnderecoPessoa", b =>
                {
                    b.HasOne("crud_accounts.Models.Pessoa", "Pessoa")
                        .WithOne("Endereco")
                        .HasForeignKey("crud_accounts.Models.EnderecoPessoa", "PessoaForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("crud_accounts.Models.TelefonePessoa", b =>
                {
                    b.HasOne("crud_accounts.Models.Pessoa", "Pessoa")
                        .WithOne("Telefone")
                        .HasForeignKey("crud_accounts.Models.TelefonePessoa", "PessoaForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
