// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crud_accounts.Models;

namespace crudAccounts.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20210225123009_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("crud_accounts.Models.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("EnderecoPessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("uf")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Enderecos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29685671-fd15-4279-a448-448170b4f3e1"),
                            Bairro = "Centro",
                            Cep = "20260525",
                            Complemento = "casa 23",
                            EnderecoPessoaId = new Guid("c890ddf9-139b-43e9-888a-2d5103e746fa"),
                            Logradouro = "Rua Sete de Setembro",
                            Municipio = "Rio de Janeiro",
                            Numero = "15",
                            uf = "RJ"
                        },
                        new
                        {
                            Id = new Guid("87fc46f1-186c-478e-a10b-b1b639beb4e9"),
                            Bairro = "Centro",
                            Cep = "11260525",
                            Complemento = "bloco 6 ap 306",
                            EnderecoPessoaId = new Guid("c890ddf9-139b-43e9-888a-2d5103e746fb"),
                            Logradouro = "Avenida Paulista",
                            Municipio = "São Paulo",
                            Numero = "1205",
                            uf = "SP"
                        },
                        new
                        {
                            Id = new Guid("871ff23b-1ef6-45ff-8052-65807537e78b"),
                            Bairro = "Bangu",
                            Cep = "21280525",
                            Complemento = "casa 5",
                            EnderecoPessoaId = new Guid("c890ddf9-139b-43e9-888a-2d5103e746fc"),
                            Logradouro = "Avenida Ministro Ary Franco",
                            Municipio = "Rio de Janeiro",
                            Numero = "2255",
                            uf = "RJ"
                        });
                });

            modelBuilder.Entity("crud_accounts.Models.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<Guid?>("EnderecoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Pessoas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Cpf = "111548",
                            Nome = "Herb Hancock",
                            Rg = "21514151"
                        },
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b32"),
                            Cpf = "1252632545",
                            Nome = "Chick Corea",
                            Rg = "207255136"
                        },
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b31"),
                            Cpf = "111548",
                            Nome = "Charlie Parker",
                            Rg = "153526548"
                        });
                });

            modelBuilder.Entity("crud_accounts.Models.Telefone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<Guid>("TelefonePessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("TelefonePessoaId");

                    b.ToTable("Telefones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7716442a-f850-4123-ac51-40c3b1a7b7e2"),
                            Numero = "985635241",
                            TelefonePessoaId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Tipo = "Celular"
                        },
                        new
                        {
                            Id = new Guid("1a54484a-a5e7-4e8a-9b12-a61d952b0cfe"),
                            Numero = "975859654",
                            TelefonePessoaId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b32"),
                            Tipo = "Celular"
                        },
                        new
                        {
                            Id = new Guid("1cdaf6ee-2630-4cd0-853f-1c094501ba7a"),
                            Numero = "312524684",
                            TelefonePessoaId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b31"),
                            Tipo = "Fixo"
                        },
                        new
                        {
                            Id = new Guid("7bc39bf5-c23e-4673-9a2e-1dafe3dca1c8"),
                            Numero = "985652541",
                            TelefonePessoaId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b31"),
                            Tipo = "Celular"
                        });
                });

            modelBuilder.Entity("crud_accounts.Models.Pessoa", b =>
                {
                    b.HasOne("crud_accounts.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId");
                });

            modelBuilder.Entity("crud_accounts.Models.Telefone", b =>
                {
                    b.HasOne("crud_accounts.Models.Pessoa", "Pessoa")
                        .WithMany("Telefones")
                        .HasForeignKey("TelefonePessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
